### ISSUE TITLE
empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:

### ISSUE THREAD

**Issue by hhhglq** [YuxiangZhang-BIT/IEEE_TGRS_LDGnet#12]
D:\Program Files\anaconda3\envs\sde\lib\site-packages\torch\serialization.py:707: UserWarning: 'torch.load' received a zip file that looks like a To
rchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
Traceback (most recent call last): 
  File "train_queue.py", line 221, in <module> 
    model = LDGnet(embed_dim,
  File "E:\learn task\IEEE_TGRS_LDGnet-main\model_queue.py", line 159, in __init__
    self.visual = D_Res_3d_CNN(1,8,16,num_classes, vision_patch_size, inchannel, embed_dim)
  File "E:\learn task\IEEE_TGRS_LDGnet-main\model_queue.py", line 46, in __init__
    self.classifier = nn.Linear(in_features=self._get_layer_size(), out_features=CLASS_NUM, bias=False)
  File "D:\Program Files\anaconda3\envs\sde\lib\site-packages\torch\nn\modules\linear.py", line 85, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, boo
l pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memo
ry, bool requires_grad)

**Comment by KaiyuanShi** [comment]
请问这个问题您解决了吗？

**Comment by Morjawhoa** [comment]
原因是
self.classifier = nn.Linear(in_features=self._get_layer_size(), out_features=CLASS_NUM, bias=False)
中的CLASS_NUM是个浮点数而不是整数，找到源头给它改成整数就好了
